services:
  # Backend API Server
  - type: web
    name: pdfchat-backend
    runtime: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health

